# Generated by Django 6.0.4 on 2026-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("vibration", models.FloatField()),
                ("noise", models.FloatField()),
            ],
        ),
    ]
