# Generated by Django 6.0.4 on 2026-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
