# Generated by Django 6.0.4 on 2026-04-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_device_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vibration_during_fault", models.FloatField()),
                ("noise_during_fault", models.FloatField()),
                (
                    "fault_type",
                    models.CharField(
                        choices=[
                            ("vibration_fault", "Vibration Fault"),
                            ("noise_fault", "Noise Fault"),
                        ],
                        default="noise_fault",
                        max_length=20,
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.device",
                    ),
                ),
            ],
        ),
    ]
