# Generated by Django 6.0.4 on 2026-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_fault"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="fault_type",
            field=models.CharField(
                choices=[
                    ("vibration_fault", "Vibration Fault"),
                    ("noise_fault", "Noise Fault"),
                    ("both_faults", "Both Faults"),
                ],
                default="noise_fault",
                max_length=20,
            ),
        ),
    ]
