# Generated by Django 6.0.4 on 2026-04-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_alter_fault_fault_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fault",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
